src/lib.rs, src/progress.rs
this fixes issue #22 (request for percent key option in style templates)
This is my first time contributing and I'm happy to flesh out this PR for it to be accepted.
=> Add `percent` key in progress style template

src/progress.rs
I thought that using "match" would improve readability.
I am sorry if I used "else if" for some reason.
=> Change conditional branch by 'else if' to 'match'

README.md
Took me a little bit of effort to see which was which, thought this might be useful to others.
=> Add source file links for each example gif

src/progress.rs
Should help with issue #8. Sorry about the formatting changes, I had format on save enabled. If you mind I can redo the PR. Looking forward to your feedback!
=> adds wrapper for reader

src/progress.rs
Fixes #94.
I believe this might also fix #18.
=> MultiProgress now honors refresh rate

src/progress.rs
=> Properly handle changing the draw target of a ProgressBar already added to a MultiProgress

src/progress.rs
=> Expose ProgressBar state through is_finished()

src/progress.rs
Currently sets progress to seeked-to position in file.
Could instead also set progress to max(progress, position).
=> enabled Seek on ProgressBarRead

src/lib.rs, src/progress.rs
Very similar to my last pull request, just passes straight through to the underlying writer.
=> Enabled Write on ProgressBar"Read"

examples/multi-tree.rs, src/progress.rs
Fixes https://github.com/mitsuhiko/indicatif/issues/177
=> Implement `insert` method for `MultiProgress`

src/style.rs
Commit 3cbd533da3eda9162da8955ead6218a022b0604b shadowed the floating-point
`fill` variable with the integer number of entirely-filled characters in the
progress bar. We still need the floating-point progress to pick the fine-grained
progress character: after that commit, `(fill * n) % n` is always 0, so we
always use the last fine-grained character.
Fix this by using a different name for the integer progress.
While I'm there, try to make the function easier to read:
- Use `str::repeat`.
- Rename some variables and add comments.
- Remove the unnecessary `pct` variable.
- Skip the selection of a fine-grained character when we have exactly one.
- Use `fill.fract()` instead of modulo to discard the integer part of progress.
This should make it difficult to reintroduce the same bug.
Fixes …
=> Fix fine-grained progress bars

examples/cargo.rs
Small terminal (80 lines)
Big terminal (> 80 lines)
=> Add cargo example

src/progress.rs
I was having performance issues where a 20sec process without progress bar would take above 1h with it.
`ProgressDrawTarget::stderr_with_hz(25)` did not seem to have any effect.
`ProgressBar::set_draw_delta` showed a significant impact but my input can vary from few Kb to several Gb and picking an arbitrary % for the update isn't an option. 
This is what solves the issue for me.
=> Add the ability to set a redraw rate on progress bar

examples/download-speed.rs
=> Fix example download-speed on 80 width terminal

src/iter.rs
=> Expose progress in ProgressBarIter

src/progress.rs
=> Steady tick should check if the update interval has changed

src/progress.rs
Although implemented differently, the logic for setting "finished" in join_impl
is identical to that in is_done.
Move is_done from MultiProgress to MultiProgressState so we can reuse it when
setting "finished", keeping the implementation that is easier to follow.
=> Refactor to remove a bit of duplicated logic from MultiProgress

src/progress.rs
The `MultiProgress` draw target was not actually reporting the width of the underlying `ProgressDrawTarget`, and would instead always report the width of `Term::stderr()`.
Because `Term` does not support writing to arbitrary file handles (yet... https://github.com/mitsuhiko/console/pull/93), this issue would have been relatively hard to detect: a `MultiProgress` would need to have been started against `stdout` with a _separate_ TTY on `stderr`. But when used against an arbitrary file handle, the result was that the width fell back to a hardcoded value.
=> Properly query the width of a MultiProgress draw target.

examples/multi-tree.rs
This shortens the example. The original implementation used a custom rng
implementation to [avoid rand dependency](https://github.com/mitsuhiko/indicatif/pull/178#discussion_r436044780), however it's already used as a dev-dependency, so it shouldn't matter.
=> Switch custom Rng implementation for rand dependency

src/progress.rs
See #187 for context
cc @Stargateur
=> ProgressBar drop should ignore draw delta

src/progress.rs
Nearly every call to RwLock was write() defying it's advantage over
Mutex. Additionally, Mutex<T> implements Sync for T: Send, contrary
to RwLock<T> which implements Sync for T: Sync, which is a bit harder to
satisfy and thus less versatile.
=> Use Mutex instead of RwLock in ProgressBar

src/progress.rs
Reference https://github.com/mitsuhiko/indicatif/commit/7bc51dfc3c42c4fbd3f742681ae229f0e0e7d2bf#r48261699
=> Rename ProgressDrawTarget::to_term to term

src/utils.rs
Size reduced from 72 bytes to 48 bytes.
=> Compress Estimate struct

src/progress_bar.rs
=> Improve `set_draw_target` docs

examples/download-speed.rs, examples/download.rs
Related https://github.com/mitsuhiko/indicatif/issues/263#issuecomment-817138712
=> Fix download examples templates

src/utils.rs
Related to https://github.com/mitsuhiko/console/pull/98.
=> Update expand_template regex to recognize from_dotted_str() 256 colors

src/draw_target.rs
fix https://github.com/mitsuhiko/indicatif/issues/342
=> Add an extra space to the last progress line

src/progress_bar.rs
As in the title.
Thanks for making the crate :)
=> WeakProgressBar::new() should not take self

.github/workflows/rust.yml, src/lib.rs, src/progress_bar.rs, src/state.rs, src/term_like.rs
=> Public ProgressState

Cargo.toml, src/in_memory.rs, src/iter.rs, src/lib.rs, src/progress_bar.rs, src/rayon.rs
=> Use doc(cfg) to improve docs.rs documentation

src/style.rs
Fix #431.
I did not delve into the inner code, so I'm not sure whether it's possible to simply remove this code without causing other bugs.
I ran `cargo test` locally and all tests passed. `cargo run --example download` now works fine too.
=> fix: first style of wide elements was ignored

src/style.rs
=> Fix the wrong link about `template`

.github/workflows/rust.yml
=> simplify build matrix

src/draw_target.rs, src/multi.rs, src/progress_bar.rs
=> Fix #503: don't deadlock when double-adding pb

.github/workflows/rust.yml
In particular, avoid lots of warnings about outdated Actions.
=> Simplify and update CI workflow

src/multi.rs
=> Fix a potential overflow with a saturating add.

src/state.rs
@chris-laplante what do you think of this? Seems like a more logical order for things to happen in... (Found after spelunking in the context of #578.)
=> Tick ProgressTrackers before drawing

src/draw_target.rs, src/multi.rs, src/state.rs
Fixes #602. @cvijdea-bd can you check whether this behaves as you expect?
=> Skip drawing MultiProgress if backing draw target is hidden

src/draw_target.rs, tests/render.rs
Fix for #670.
Will work on a reproducing the issue and creating a test for it, but in the meantime this fixes the issue experimentally.
=> Fix double prints

Cargo.toml
To get @jaheba's recent perf improvements out.
=> Bump version to 0.17.10
