- src/lib.rs
This updates docstrings to fix the following two test failures:
```
---- _0 stdout ----
error: expected type, found `^`
|
2 | [<^>]           for an optional alignment specification
|   ^
---- _1 stdout ----
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
|
7 |     bar.inc();
|         ^^^ expected 1 parameter
```
> lib: fix docstring tests

- src/progress.rs
This sanitizes percentage calculation, by avoiding NaN and capping
results between 0.0 and 100.0.
Fixes https://github.com/mitsuhiko/indicatif/issues/12
> progress: sanitize percent() values

- src/progress.rs
Note: this is based on top of https://github.com/mitsuhiko/indicatif/pull/14, please consider landing that first.
Fixes https://github.com/mitsuhiko/indicatif/issues/13
> progress: use saturating sub to avoid underflows

- Cargo.toml
- examples/tokio.rs
This adds a simple "timer with progress bar" example showing how to use indicatif together with tokio/futures.
> examples: add a tokio-based timer example

- src/progress.rs
A call to `wrap_iter()` shall consume both the `ProgressBar` and the
given `Iterator`, returning an iterable that will yield results from the
iterator while updating the progress bar.
Fixes #7.
> Add a `wrap_iter` method

- src/progress.rs
ProgressDrawTarget was unsafe impl Sync which hid a true threading
issue: multiple threads could call Sender::send simultaneously, which is
not permitted by the mpsc API.
Wrapping Sender in a Mutex not only fixes the bug but also permits us to
remove the unsafe impls. The same type is the reason for the unsafe impl
of MultiProgress; however, in that case, the call to Sender::clone is
protected by holding the write lock on MultiProgress::state.
> Fix thread safety issue.

- src/progress.rs
Closes #17.
In my program, drawing four progress bars produces horrible flickering, and this change eliminates it completely. I made it opt-in because if you change the number of progress bars while they are being drawn (e.g. by dropping a `ProgressBar` after adding it to a `MultiProgress`), then this option changes the rendering.
> MultiProgress: add option to avoid clearing terminal lines

- src/progress.rs
I have a program in which progress completes from... two ends. So, I end up both incrementing progress - when I find that I've sent a new, unique object to a server - and, decrementing the progress bar's length (when I find that the server already has the object I'm thinking about sending, and realize the server already has it, so we don't send it.) However, when my progress bar does `.set_length(0)`, it suddenly overflows by 100x! This is because the `.percent()` method calculates the progress of the progress bar as a fraction in the range `[0, 1]`, *but*, if the length of the progress bar is `0`, it returns `100`! This PR fixes this bug and renames `.percent()` to `.fraction()` to better reflect the way it does not return a number in the range `[0, 100]` but instead between `[0, 1]`.
> Rename percent to fraction; fix 100x fill bug when len == 0

- examples/finebars.rs
- src/progress.rs
This PR adds the ability to specify multiple characters for the "in progress" part of a progress bar, which
are then displayed in sequence as that part fills up.
This allows a user to show a more precise progress bar, as there can be multiple distinct steps per terminal column.
To use this feature, pass more than 3 characters to `ProgressStyle::progress_chars()`. The first and last characters are still for the "filled" and "to do" parts of the bar, but if there are multiple characters between those, they're used sequentially for the "current" part of the bar.
`examples/finebars.rs` demonstrates how this works:
[![asciicast](https://asciinema.org/a/OCrX70oy90lE2MakVLnUQyJbt.png)](https://asciinema.org/a/OCrX70oy90lE2MakVLnUQyJbt)
> Allow multiple in-progress characters for bars.

- Cargo.toml
I just noticed that the project's Cargo.toml only points to the repository via the "homepage" link, which is not supposed to direct to the repository anyway. This PR should ensure conformance and make the crate a bit more friendly.
> Rename Cargo.toml homepage field to repository

- src/progress.rs
Due to a bug in ProgressBar::format(), a bar that is roughly 100% full but no finished will currently be drawn
with a full line of "finished" characters and then an additional "head" character.
This breaks alignment in some cases, like this:
```
Bar 1 [#####=----] 55%
Bar 2 [##########=] 99%
Bar 3 [###=------] 37%
```
This PR fixes that bug.
> Fix a Bug where progress bars sometimes are one character too long.

- examples/yarnish.rs
b447ed8ce76b7e5c573d62d1d4c38298b01025ec accidentally reversed the position of the emoji and the elapsed time.
> Fixed last line of yarnish example

- examples/log.rs
- src/progress.rs
This allows logging some information without interfering with the progress bar.
```rust
extern crate indicatif;
use std::thread;
use std::time::Duration;
use indicatif::ProgressBar;
fn main() {
let pb = ProgressBar::new(100);
for i in 0..100 {
thread::sleep(Duration::from_millis(250));
pb.println(format!("[+] finished #{}", i));
pb.inc(1);
}
pb.finish_with_message("done");
}
```
Resolves #27
> Allow logging above the progress bar

- examples/fastbar.rs
- src/progress.rs
The default behavior seems to be to redraw the progress bar with any triggered update of the state (for example, using `inc(i)`, `set_position(i)`, etc).  For situations where the number of items being processed is very large, but the actual time to process each item is very small, the drawing of the progress bar dominates the overall computation time.
This pull request adds a method `set_draw_delta(n)` which limits the redrawing of the progress bar to every `n` steps, but allows the user to still call methods to update the position.  The default behavior of updating the progress bar with every update remains the same.  An example of the usage of `set_draw_delta(n)` is included which demonstrates that drawing too frequently can have significant overhead to an overall computation.  Output …
> Add option to limit how frequently the progress bar is redrawn

- Cargo.toml
- src/format.rs
- src/lib.rs
- src/progress.rs
- decimal_{bytes,total_bytes} use SI prefixes
- binary_{bytes,total_bytes} use ISO/IEC 60027-2 prefixes
Additionaly, HumanBytes now scales up to Yobibytes instead of only Tebibytes.
This introduces a new dependency on the number_prefix crate (MIT licensed).
> Add decimal and binary bytes keys in style templates

- src/progress.rs
Adds a small mention of the refresh rate to `ProgressBar::new` (closes #55). Also adds a convenience constructor to create a ProgressBar with a given draw target.
> Add a constructor taking a ProgressDrawTarget

- Cargo.toml
This decreases `*.crate` file (the one that cargo uses to build this crate)  size from 1.3MiB to 15.3KiB.
> Exclude screenshots from the crate package.

- src/progress.rs
This fixes `println` if the string contains multiple lines.
The `println` function could also now take `AsRef<str>` instead, but I didn't want to break the signature.
> Fix println for multi line strings

- src/progress.rs
Upon exiting the steady tick thread, we don't ever set `tick_thread` back to None, so nothing starts it up again!
> [steady_tick] Fix steady tick getting stuck after disabling and re-enabling.

- src/progress.rs
For #74. The optimization still works:
```
cargo run --example fastbar
Compiling indicatif v0.10.2 (/Users/vasiliua/indicatif)
Finished dev [unoptimized + debuginfo] target(s) in 4.99s
Running `target/debug/examples/fastbar`
██████████████████████████████████████████████████████████ 1048576/1048576
[Default progress bar ] Sum (1099513724928) calculated in 4 minutes
██████████████████████████████████████████████████████████ 1048576/1048576
[Draw delta is 0.005% ] Sum (1099513724928) calculated in 2 minutes
██████████████████████████████████████████████████████████ 1048576/1048576
[Draw delta is 0.01%  ] Sum (1099513724928) calculated in 2 seconds
```
> Make draw_delta default to 0 so all changes show immediately. Fixes #74

- src/progress.rs
This adds a new function: `MultiProgress::with_draw_target(draw_target: ProgressDrawTarget) -> MultiProgress` which allows to have a nicer API around creating `MultiProgress`  and more symmetry between `MutliProgress` and `ProgressBar`.
> Add MultiProgress::with_draw_target

- src/progress.rs
This adds a convenience function to `ProgressBar`. It imitates a builder function and is intended to be used as `ProgressBar::new(1234).with_style(...)`.
> Add ProgressBar::with_style convenience function

- Cargo.toml
- examples/iterator.rs
- src/iter.rs
- src/lib.rs
- src/progress.rs
While using indicatif, I had modified the iterator API to both a) work with iterator chaining and b) support parallel iterators with Rayon. The changes look like:
```rust
let mut v = vec![1, 2, 3];
// used to be:
let pb = ProgressBar::new(v.len());
for item in pb.wrap_iter(v.iter()) {
...
}
// now is:
for item in v.iter().progress_count(v.len()) {
...
}
// also parallel iterators
v.par_iter().progress().map(|i| { ... }).collect()
```
I added a feature gate so the user does not have to download Rayon if they're not using it.
I wanted to show this initial PR to see if the maintainers would be interested in either change. If so, I can go ahead and add more tests/documentation.
> Refactor iterator API, add Rayon extension

- src/progress.rs
MultiProgressBar join() method requires sub-progress-bars
to finish before join() succeds, but the default finish
method would update the state.pos to 100% obsucring the
fact that the process was incomplete.
I therefore added a new method finsih_at_current_pos()
that updates the state to DoneVisible without changing
the current position. This solves my problem.
> I needed to leave a progress bar on screen that had not completed to 100% due to errors.

- src/progress.rs
Enable to get current position
> Add get position

- examples/download-speed.rs
- src/lib.rs
- src/progress.rs
- src/style.rs
This allows printing progress bars like:
```
[00:00:01] [###>------------------------------------] 18.31MB/220.52MB (15.14MB/s, 14s)
```
> Add style key for speed in steps/bytes per second

- src/progress.rs
Hi!
I've spend some time trying to figure out why my messages are not visible, so here are the clarifying docs so that the next person doesn't have to! :)
> Clarify confusing bits about messages

- src/progress.rs
`multi` example is broken after #59 , it doesn't redraw the progress bar after set position to 0.
> fix: should redraw progress bar after set position

- src/progress.rs
This is useful when new work arrives while tracking the progress of existing work.
> Support increasing the length of the progress bar with a delta.

- src/utils.rs
> Set initial 'started' value for Estimate::new()

- src/progress.rs
- tests/multi-autodrop.rs
This is an alternative way to implement this. `Drop` is directly implemented on `ProgressState`, which is IMHO semantically more correct than the current solution: 821ed338e7b648183803cbb0ad118cf12e5a5616.
I also added my example as a proper test case.
> Only finish the progress bar on last refcount drop

- examples/long-spinner.rs
- src/iter.rs
- src/lib.rs
- src/progress.rs
- src/style.rs
First of all hi @mitsuhiko and thank you for this great crate 👍.
I wanted to have the functionality to use wider spinners that support more than one single char at a time. Therefore I switched the `Vec<char>` with a `Vec<String>` and updated related functions accordingly.
Then all the spinners from the [cli-spinners](https://github.com/sindresorhus/cli-spinners/blob/master/spinners.json) project can be supported.
This is also helpful when using emojis as ticker, because some of them consume 2 characters on the console and need to be cleared with two whitespace chars in the end respectively.
I had to deprecate `get_tick_char` and `get_final_tick_char` as there is no good way of trimming down a `str` to a single `char`.
> Allow spinners longer than one character

- src/progress.rs
I use `abandon()` so a user can still see the incomplete progress bar after a task fails.
Was there already a way to accomplish this? I couldn't find one.
Thanks,
Cory
> add ProgressBar::abandon(), abandon_with_message()

- src/progress.rs
> Clarify when the message is visible when running with_message functions

- Cargo.toml
- examples/fastbar.rs
- src/iter.rs
- src/lib.rs
- src/style.rs
previously using two-wide characters as progress chars made the bar overflow.
also aded a bit more unicode-awareness (grapheme-clusters instead of simple chars)
and made the spinner a bit more efficient (Box<str> instead of String) as it never gets modified.
> Unicode awareness for progress_chars

- src/progress.rs
If there are multiple progress bar updates happening concurrently only one update will be shown immediately. The rest of the updates will only be shown upon the next update that's happening after the refresh rate cooldown in ProgressDrawTarget elapses. This change implements grouping updates to prevent that behavior.
Example code below shows this issue. Without this change the 1st bar is always one step ahead of the 2nd, however with this change the bars are aligned most of the time (not always aligned presumably because `pb.inc` is slower than a `MultiProgress` update).
```rust
use indicatif::{MultiProgress, ProgressBar};
use std::thread;
use std::time::Duration;
fn main() {
let mpb = MultiProgress::new();
let pb1 = mpb.add(ProgressBar::new(30));
let pb2 = mpb.add(ProgressBar::new(30)); …
```
> Implement update grouping

- src/progress.rs
MultiProgress was only passing on the force_draw flag to its draw_target if it
is set on the last ProgressDrawState in a group.
Fix this by handling force_draw similarly to orphan_lines: initialize it outside
the loop, accumulate (set it to true if necessary) as we receive updates, clear
it (set it back to false) after drawing.
I think it is currently not possible to actually hit this bug: the only places
producing a ProgressDrawState with force_draw set are println() and
MultiProgress itself, using println() always forces a draw because orphan_lines
is nonzero, and it looks like it is not currently possible to nest a
MultiProgress in another MultiProgress. I only noticed this because I was making
an unrelated change to this code. But we might as well fix it to avoid future
problems.
> Fix potential loss of force_draw when grouping MultiProgress updates

- src/lib.rs
- src/progress.rs
- src/style.rs
This seemed like an obvious, small improvement – tqdm shows the total extrapolated duration, why couldn't indicatif?
> Implement duration (eta + elapsed) for formatting

- src/iter.rs
- src/lib.rs
Closes #195 
Breaking change: removed `ParallelProgressIterator::progress` due to it's confusing nature
> Rayon related improvements

- src/progress.rs
In some cases, when creating progress bars that have both a prefix and message (set immediately after creation using set_prefix and set_message), I found that bars were initially being drawn incorrectly due to the refresh frequency limit preventing them from being redrawn after the first set_* call.
In order to allow bars to be fully initialized before being drawn, I have added some additional builder-style functions to allow these values to be set before the bar is drawn.
The following builder-style functions have been added:
* with_prefix
* with_message
* with_position
> Add builder-style functions for initializing prefix, message and position

- src/lib.rs
- src/style.rs
Format bytes per second for human readability using  ISO/IEC prefixes.
I'm using indicatif in a torrent creator[0], and although it's a bit unusual to format data/second with SI prefixes, I'm using SI prefixes in other places, so I'd like to be consistent.
Thanks for this library! My program will have much prettier output because of indicatif.
[0] https://github.com/casey/intermodal
> Add `binary_bytes_per_second` state formatter

- src/progress.rs
Closes #213
If behavior like `pb.println(123)` should be allowed, i.e. anything that `impl Display`/`ToString` then merge #213 instead.
However, the behavior of `ToString` would result in:
- 2 needless clones occurring for `pb.println("Foo")` and 
- 1 needless clone for `pb.println(String::from("Foo"))`.
While changing to `AsRef<str>` would:
- Remove 1 existing needless clone occurring when doing `pb.println("Foo")` _(As `msg.into()` needlessly converts it into a `String` which is immediately discarded after `collect()`.)_
> If you call `pb.println(String::from("Hello World"))`, then with `Into<String>` then the `String` is moved. However if you change it to `ToString` then the string is needlessly cloned.
>
> Now, what would be better, would be to change it to `AsRef<str>`. Because …
> Removed needless clone

- src/iter.rs
- src/lib.rs
Hi,
Rayon exposes a supertrait of `ParallelIterator`, `IndexedParallelIterator`, which has a `len` method. This PR adds a new progress trait, `IndexedParallelProgressIterator`, that wraps `IndexedParallelIterator` and makes the `progress` method work in the same way `ProgressIterator` does with `Iterator`'s `size_hint` method, so we don't have to rely on `progress_count`.
I'm pretty new to working with Rust, and I'm not sure this is the best way of going about this. I tried to add an impl of `ParallelProgressIterator` for `IndexedParallelIterator`, but the compiler complained that the implementations were ambiguous because an `IndexedParallelIterator` is also an `ParallelIterator`. Maybe the extra trait makes this API worse than just getting people to use `progress_count`.
> Add indexed parallel iterator support

- src/utils.rs
this pr fix var match in progress style like this:
before:
after:
> fix var match

- src/progress.rs
Required in order to use `wrap_read` together with flate2's `GzDecoder` or any other decoder built on `BufRead`.
```rust
use flate2::bufread::GzDecoder; // flate2 = "1.0"
use indicatif::ProgressBar;
use std::fs::File;
use std::io::BufReader;
use tar::Archive; // tar = "0.4"
fn main() {
let file = File::open("...").unwrap();
let len = file.metadata().unwrap().len();
let buf = BufReader::new(file);
let pb = ProgressBar::new(len);
let input = pb.wrap_read(buf);
let archive = Archive::new(GzDecoder::new(input));
// ...
}
```
Before:
```console
error[E0277]: the trait bound `ProgressBarWrap<BufReader<std::fs::File>>: BufRead` is not satisfied
--> src/main.rs:13:47
|
13 |     let archive = Archive::new(GzDecoder::new(input));
|                                               ^^^^^ the trait …
```
> BufRead for ProgressBarWrap

- src/progress.rs
I believe it makes more sense for `Instant` to be stored in `ProgressDrawTargetKind::Term`. The `Instant` is used for checking the rate of drawing only. Now, when it is stored in the draw target it is more accurate (as it actually checks the time of the last draw instead of the time when an update was crated) and reduces memory usage.
> Move Instant from ProgressDrawState to ProgressDrawTargetKind::Term

- src/progress.rs
This clone call is actually necessary. Without it a now-fixed bug will not be triggered. To test this change `ProgressDrawTarget::apply_draw_state` (line 165) from:
```rust
ProgressDrawTargetKind::Remote { idx, ref chan, .. } => {
return chan
.lock()
.unwrap()
.send((idx, draw_state))
.map_err(|e| io::Error::new(io::ErrorKind::Other, e));
}
```
to:
```rust
ProgressDrawTargetKind::Remote { idx, ref chan, .. } => {
chan
.lock()
.unwrap()
.send((idx, draw_state))
.map_err(|e| io::Error::new(io::ErrorKind::Other, e)).unwrap();
}
```
> Add back clone required to trigger a bug

- src/progress.rs
This variable was always `None` and used in only one place. It was
probably created to cache the target's width, however it's not too
expensive to check and can create problems after resizing a terminal (a
`wide_xyz` placeholder will use wrong width)
> Remove ProgressState::width

- src/style.rs
This reduces ProgressStyle's size by 16 bytes.
Cow is useful when occasionally mutating the data inside, however
it was never mutated, and only read from. The only, negligible, benefit
is when reusing a single static str as a template across multiple
progress bars (as the template would be stored in memory only once;
as an example the template in download-continued is 106 bytes),
however the current API doesn't even expose such a functionality despite
it being easily implementable.
> Change ProgressStyle::template from Cow<'static, str> to Box<str>

- src/progress.rs
- src/utils.rs
Up until now Estimate would be in a fully initialized state after
calling `new`, however after calling `reset` it would get fully
initialized only on the next call to `record_step`. This is an
unexpected disparity that this commit unifies. Now, when calling `reset`
you must also provide a `start_value`, so that the Estimate can not be
in a semi-initialized state anymore.
> Unify Estimate behavior

- src/iter.rs
- src/lib.rs
- src/progress.rs
- src/rayon.rs
- src/style.rs
As discussed in a [tangentially related PR](https://github.com/mitsuhiko/indicatif/pull/240), it would be nice to have an API for specifying how a progress bar should be `finish()`ed by default when it is dropped or when an iterator it is wrapping has finished.  This PR proposes such an API by adding a `ProgressFinish` enum to the `ProgressStyle`, which can be used like this:
```rust
let pb = ProgressBar::new().with_style(
ProgressStyle::default_bar().on_finish(ProgressFinish::AndClear)
);
```
In this example `pb` will automatically have `finish_and_clear()` called on it when it is dropped, unless the user manually calls one of the other `finish()` methods before dropping.
This is especially useful for set-it and forget-it style progress bars used in iterators.  For example:
```rust
const …
```
> Add ProgressFinish API

- src/progress_bar.rs
- src/state.rs
This is basically the same as #187 except that the problem wasn't in `impl Drop` but in `fn abandon` this time
> Fix deadlock when using `ProgressBar::abandon`

- examples/multi-tree-ext.rs
- examples/multi-tree.rs
Modified `multi-tree` example to demonstrate `MultiProgress` modifications. Demo:
> Update multi-tree example

- src/progress_bar.rs
A few methods of the progress bar underlying state can be useful to external operator, adding wrapper method to expose them.
> Make state methods publicly available

- src/format.rs
- src/lib.rs
HumanBytes displays wrong binary prefix. For example, 1024 bytes should be "1KiB" but not "1KB".
> Fix HumanBytes display

- src/state.rs
- src/style.rs
This changes default behavior - now a progress bar without an explicitly set on_finish will call `finish`, when previously it would call `finish_and_clear` ([`src/style.rs:103`](https://github.com/mitsuhiko/indicatif/compare/main...mibac138:on-finish?expand=1#diff-5452dc5fb15e73154c0ecc33e87a14379a97f817fe0cdb0fb9d17df712feb8fbR103)). Also, `on_finish` won't be reset every time `finish_with_style` is called.
> Unwrap ProgressFinish

- examples/cargo.rs
Hello thanks for the great crate! I loved all the examples and just wanted to improve on the `cargo` example a bit. Just a quick overview of the changes:
- Bumped up the time to "build" each crate so it's easier to follow what's happening
- Added a `Compiling ...` line for each crate
- This did involve storing a dummy version as well
- Added a `Finished ...` line to better match `cargo`
> Have cargo example more closely match cargo

- Cargo.toml
Fixes #280
This also disables the `ansi-parsing` feature in `console`, I don't know if that breaks anything or not.
> Make "unicode-width" dependency actually optional

- src/state.rs
This fixes an reachable `unreachable!()` statement.
This might not be the approprite fix, although it resulted in no panic
in the code I used to test it, so it seems appropriate as a first idea
for a proper fix.
---
If you think this is a good first idea, please release it as a patchlevel update (`v0.16.1`)!
Related to #285 (but there might be a better fix)
> Fix: Code is actually reachable

- src/rayon.rs
ProgressFolders represent only a part of the whole iterator and
so shouldn't finish progress bars as they don't have knowledge
of the completion of the rest of folders and otherwise could
prematurely finish a progress bar. Progress bar will still finish
when the iterator is dropped.
Fixes #289
> ProgressFolder shouldn't finish progress bars on completion

- examples/finebars.rs
- examples/morebars.rs
- examples/multi-tree-ext.rs
- examples/multi-tree.rs
- examples/multi.rs
- examples/yarnish.rs
- src/progress_bar.rs
- src/state.rs
- tests/multi-autodrop.rs
This change moves drawing of MultiProgress from the join() thread to the child ProgressBar updates.  fixes #125, #33 and lay groud work for work on #205
**It is backwards-incompatible.**
It is based on the work of @marienz  in #231 more discussion and detail on that pull request.
> Remove MultiProgress::join() based on #231

- src/state.rs
- src/utils.rs
Fixes #10. 
`Estimate::time_per_step()` returns a `Duration`, which has a limited precision of 1ns. Unfortunately, this makes it impossible to handle high progress rates (>1 billion items per second).
The proposed solution is to add `seconds_per_step()` and deprecate time_per_step() in a future release. This PR intentionally leaves the old APIs in place to preserve backwards compatibility.
> Fixed precision issue at high progress rates

- src/format.rs
- src/state.rs
Fixes #294. The behaviour before this pull request was the following (taking the example of the hour but almost every other unit would be equivalent)
```
3 hours (until 180 minutes are remaining)
2 hours (until 120 minutes are remaining)
1 hour (until 60 minutes are remaining)
59 minutes (until 59*60 seconds are remaining
58 minutes (etc.)
```
We want to replace this truncation with a proper rounding. There are several ways to go about that.
1. Perform the computations in float or in integers. I chose to use floats because of the easier rounding.
2. Decide what to display between a unit and the next. Intuitively, one could want to see:
```
3 hours (until 2 hours and 30 minutes are remaining)
2 hours (until 90 minutes are remaining)
1 hour (until 59 minutes and 30 seconds are remaining)
59 …
```
> Fix rounding of time by HumanDuration

- examples/download.rs
- src/progress_bar.rs
- src/state.rs
- src/style.rs
This PR makes the `pos` and `len` fields of `ProgressState` to have `pub` visibility. I changed the `per_sec` method of `ProgressState` to return an `f64`, and `{per_sec}` in the template now rounds to an integer via the `format!` macro (rather than truncating by default), and is explicitly truncated in other places of the code. With this patch, you can now use `.key(...)` method from `ProgressStyle` to add a custom formatting function and template key. This PR also adds another example to show the usage of this feature.
I also changed the `position` method to just be 2 separate methods for returning the position and length, because the usage beforehand where `position()` was called before matching the template keys and then you would just reuse those for `{pos}` and `{len}` now seems …
> Add ability to customize template keys

- src/iter.rs
This avoids sending a stream_position update and also preserves optimizations that the underlying object may have made for stream_position.
For example, when wrapping a `BufReader` object, adding this impl allows the use of `.stream_position()` in functions that take a generic `Seek` object without causing the performance drop associated with the default impl of `stream_position` calling `seek(SeekFrom::Current(0))` and throwing away the buffer each time.
> Pass through stream_position in ProgressBarIter

- Cargo.toml
- src/iter.rs
- src/progress_bar.rs
Added support for tokio Read, Write and Seek traits to allow for using the ProgressBar with tokio async io traits by wrapping them in ProgressBarIter.
> Added AsyncRead and AsyncWrite support for ProgressBar

- examples/iterator.rs
I've added the sleep to be able to see the bars when I run the example. They were very quickly done without a `sleep`.
> Add sleep in iterator example to see bars

- Cargo.toml
- examples/multi-tree-ext.rs
- examples/multi-tree.rs
- src/style.rs
The motivation is that console already uses once_cell, so this should in theory decrease the total number of dependencies.
Note: The formatting has changed, do you happen to use some rustfmt flags? if so it would be better if you have a `.rustfmt.toml` file.
> Use once_cell instead of lazy_static

- src/progress_bar.rs
This PR adds `ProgressBar::with_elapsed()` which provides a way to override the elapsed time of a progress bar.
This is useful for scenarios where you dynamically create additional ProgressBars for "sub-tasks" and want to preserve the elapsed time in the output. Since ProgressBar exposes the elapsed time as a Duration, `with_elapsed` is more ergonomic than `with_start_time`.
> ProgressBar: Add with_elapsed for overridding elapsed time

- src/progress_bar.rs
Add `insert_from_back` method to `MultiProgress`
> feat: MultiProgress insert_from_back

- src/lib.rs
Fix https://github.com/mitsuhiko/indicatif/issues/328
> Document interaction between `wide_bar` and `wide_msg`

- Cargo.toml
indicatif is already a very popular crate, but this helps with discoverability
> Add categories keyword to Cargo.toml

- src/draw_target.rs
- src/progress_bar.rs
- src/state.rs
This function hides the progress bar temporarily, execute `f`, then redraws the progress bar, which is useful for external code that writes to the standard output.
The idea is originally raised in #92.
It is planned to eventually create a global function like `ProgressBar::instance` that allows calling `suspend` from e.g. a log handler, but this currently doesn't generalize to `MultiProgressBar` which could be an obstacle.
> Implement ProgressBar::suspend

- src/iter.rs
> Add builder methods for ProgressBarIter

- src/draw_target.rs
Fix https://github.com/mitsuhiko/indicatif/issues/334
The math seems to checkout, but I can't be 100 % confidant
- I prefer not to change console because this current behavior could be relied on by crates
- I'm using write_str which is doc_hidden is that ok?
> Don't add an extra line after the progress bar

- src/format.rs
I think it's better to have some sort of separator (e.g. space) between numbers and their units.
> Add a space between numbers and their units

- src/style.rs
From style.rs, line 385:
```
impl<'a> WideElement<'a> {
fn expand(
self,
cur: String,
style: &ProgressStyle,
state: &ProgressState,
buf: &mut String,
) -> String {
let left = state.width().saturating_sub(measure_text_width(&cur));
let left = left + 1; // Add 1 to cover the whole terminal width
```
When the `improved_unicode` feature is off, `measure_text_width` just counts characters. Consider the case of rendering the default progress bar style. `cur` will be something like `\x00 0/10`. In this case `measure_text_width` returns the width as 6 since it is counting the null byte. This bug is what led to the addition of line 394 to offset it (in #350):
let left = left + 1; // Add 1 to cover the whole terminal width
When `improved_unicode` is on, `measure_text_width` correctly returns 5 …
> Fix wide element styling to work with 'improved_unicode' feature as well

- src/draw_target.rs
- src/progress_bar.rs
- src/state.rs
- src/style.rs
This clarifies the internal structure and avoids reallocating some buffers.
> Draw progress bars into draw states

- .github/workflows/rust.yml
- Cargo.toml
- src/draw_target.rs
- src/in_memory.rs
- src/lib.rs
- src/term_like.rs
These changes make it possible to write tests that compare the visual output of progress bars to expected output.
The `TermLike` trait provides a common abstraction over the `console::Term` type and the new `InMemoryTerm`. The trait is made public so that users can develop their own custom draw targets, should the need arise.
`InMemoryTerm` is basically just a vector of lines, with a cursor that tracks the current line. 
Still to-do:
> introduce TermLike trait; add InMemoryTerm 

- src/draw_target.rs
The user progress template can exceed the terminal width, so we use a
`saturating_sub` when calculating padding spaces to clamp it at 0 in
this case.
fix https://github.com/console-rs/indicatif/issues/358
> Fix panic when calculating padding spaces

- src/draw_target.rs
- src/multi.rs
- src/progress_bar.rs
- src/state.rs
This is a regression from my work on drawing into draw states. Specifically, before 57e6ee282d5dd71f7846bd28e3f0369fd3f6d452 `force_draw` was passed in as part of the `ProgressDrawState`, but after that commit it was no longer handled correctly. Fixes #368.
@chris-laplante I think this is pretty much what you were suggesting, right? If you want to give it a quick look that would be great.
> Pass force_draw into drawable()

- src/state.rs
This is especially relevant when speed varies a lot. Then confusing things like this https://github.com/probe-rs/probe-rs/issues/801 can happen. This is unfortunately only barely, if at all, visible in the examples as speed, whilst varying a little, is steady.
> Do not use boxcar windowing when displaying the final total of the speed

- examples/fastbar.rs
- src/multi.rs
- src/progress_bar.rs
- src/state.rs
We now have rate limiting in the draw target, which is takes care
of most of the costs of drawing. Limiting earlier is not as
helpful in terms of performance, and reduces accuracy.
> Remove draw limiting from the ProgressBar state

- examples/multi.rs
- src/draw_target.rs
- src/in_memory.rs
- src/multi.rs
- tests/render.rs
Work-in-progress pull request for implementing println. This does not currently work as nothing is printed for some reason. I have reason to believe it is due to an interaction with e46ca83e, since if you change the line below to `m.println("Starting...\n\n")` it works.
> MultiProgress: add println and suspend implementation

- src/style.rs
> Account for alignment when truncating

- src/state.rs
This is happening in some of my CI runs, like here: https://github.com/arxanas/git-branchless/runs/5581044721?check_suite_focus=true
> Fix `Estimator` panic

- src/draw_target.rs
- src/progress_bar.rs
- src/state.rs
- src/style.rs
> Fix addition overflow in `AtomicPosition`

- src/multi.rs
Before this change it is possible for a combination of Ticker and
MultiProgress to deadlock due a lock inversion. Consider this code:
let mp = MultiProgress::new();
let s = mp.add(ProgressBar::new_spinner());
s.enable_steady_tick(Duration::from_millis(50));
let p0 = mp.insert_after(&s, ProgressBar::new(10));
Inside `Ticker`, a lock on `BarState` is acquired and then the state is
drawn to the draw target via `BarState::draw()`. `draw` calls
`self.draw_target.width()` which in the case of `MultiProgress` locks
`MultiState`.
Meanwhile, the call to `insert_after` calls `MultiProgress::internalize`
which locks the `MultiState`. Then `MultiState::insert` (in the case of
`insert_after` and `insert_before`) locks the `BarState` in order to
read the index.
So we have thread 1 locking in this …
> MultiProgress:insert_{after, before}: grab pb index immediately to avoid deadlock with Ticker

- examples/multi-tree-ext.rs
- examples/multi-tree.rs
- examples/tokio.rs
- examples/yarnish.rs
- rustfmt.toml
- src/lib.rs
- src/progress_bar.rs
- src/rayon.rs
- src/state.rs
- src/style.rs
- src/term_like.rs
- tests/multi-autodrop.rs
- tests/render.rs
Here's a first draft of how I think `Ticker` should work. 
So far the only testing I've done is to confirm that the long-spinner example works OK. I have not yet tested the modified version of it (which uses the `Barrier`s).
Fixes #416.
TODO:
> rework Ticker (fix #416)

- rustfmt.toml
This contains unstable options, which results in warnings when running
stable rustfmt. That doesn't seem like a good experience to me.
@chris-laplante what do you think? IMO this is a little too ugly (for outside contributors, too) to keep like this. Alternatives:
* We can enforce nightly rustfmt in CI, but sucks if local rustfmt is different from CI
* We could ignore rustfmt.toml, so you can keep it around and I'll review manually?
> Remove rustfmt config again

- examples/download.rs
- src/lib.rs
- src/state.rs
- src/style.rs
Very much a janky WIP, and some of the objects I introduced could use better naming though I avoided doing so in the interest of retaining compatibility with existing code. Haven't tested this against older rustc, but as of my current rustc version (latest stable) there are no lints from either regular check or clippy. But let me know if this seems like an ok direction and I'll revise it further.
~~Somewhen I'll modify that example to show what a more bumpy file transfer looks like, and the advantage of averaging it by the method I used.~~ done
> Stateful Formatters

- src/format.rs
- src/lib.rs
- src/style.rs
@djc here's my attempt to resolve #392.
`HumanFloatCount` largely mimics `HumanCount` with the exception that it accepts f64, and truncates the fractional part at 4 decimal places.  If the float is a whole number, it doesn't add ".0" to the end.
```rust
#[test]
fn human_float_count() {
assert_eq!("42", format!("{}", HumanFloatCount(42.0)));
assert_eq!("7,654", format!("{}", HumanFloatCount(7654.0)));
assert_eq!("12,345", format!("{}", HumanFloatCount(12345.0)));
assert_eq!(
"1,234,567,890",
format!("{}", HumanFloatCount(1234567890.0))
);
assert_eq!("42.5", format!("{}", HumanFloatCount(42.5)));
assert_eq!("7,654.321", format!("{}", HumanFloatCount(7654.321)));
assert_eq!("12,345.6789", format!("{}", HumanFloatCount(12345.6789)));
assert_eq!(
"1,234,567,890.1234",
format!("{}", …
```
> HumanFloatCount for per_sec

- src/style.rs
Misspelled the feature with an underscore instead of dash while refactoring in https://github.com/console-rs/indicatif/commit/d7851c7a467313571d71133b1729af9c5dd3b2ae.
(This feature is actually enabled by default now.)
Fixes #455.
> Fix unicode-width feature spelling

- src/progress_bar.rs
- src/state.rs
- tests/render.rs
Fix a regression from #417 to fix #457.
Of the 4 callers of `BarState::tick()`, changed three to no longer tick if the ticker is enabled:
* `ProgressBar::inc()`
* `ProgressBar::set_position()`
* `ProgressBar::update()`
The fourth is `ProgressBar::tick()`, which already only ticked if the ticker was disabled.
> Only tick if the ticker is disabled

- src/style.rs
Fixes #467, alternative to #468.
@rctlmk does this fix your original issue?
> Add Sync bound to ProgressTracker

- src/draw_target.rs
Update ProgressDrawTarget documentation to reflect the actual defaults of 20 hz instead of 15 hz.
> Update ProgressDrawTarget documentation

- src/progress_bar.rs
This was slightly confusing when I saw it in IDE.
> Correct mis-naming of variables in wrap_async_read

- src/iter.rs
By implementing `write_all` we lose granularity of progress updates
that are captured from `write`.  Therefore, remove this function.  This also brings the `ProgressBarIter`'s `Write` trait into line with the `Read` trait since that doesn't provide an implementation of `read_all`.
> Remove `write_all` from `ProgressBarIter`'s `Write` trait

- src/style.rs
The last item in tick chars/strings won't ever show unless a progress bar is finalized.  This also self-clarifies the requirement for at least two chars/strings.
Related: https://github.com/console-rs/indicatif/issues/477
> Document last char/string in tick style being the "final" state

- src/draw_target.rs
- src/multi.rs
- src/progress_bar.rs
- src/state.rs
- tests/render.rs
This implements what I described [here](https://github.com/console-rs/indicatif/issues/451#issuecomment-1204409255) (except for the resetting upon `MultiProgress::clear` or `MultiProgress::suspend`). It is ugly because it is working around a double mutable borrow that occurs when you write the code in the "obvious" way:
```rust
fn clear(&mut self, now: Instant) -> io::Result<()> {
match self.draw_target.drawable(true, now) {
Some(drawable) => {
if let Some(last_line_count) = self.draw_target.last_line_count() {
*last_line_count += self.zombie_line_count;
self.zombie_line_count = 0;
}
drawable.clear()
}
None => Ok(()),
}
}
```
Ideally, only `MultiState`/`MultiProgress` would have to know anything about `zombie_line_count`, but I fear we may have to push it deeper into the hierarchy. I will …
> Rework zombie handling to fix #451 and #464

- Cargo.toml
I think it's time -- we've cleared most of the regressions, though we're still tracking the estimator stuff in #394.
> Bump version to 0.17.1

- src/style.rs
- tests/render.rs
This PR adds support for multi-line progress messages, following #442.
The changes mostly update the drawing functions to split progress messages before counting them, so that the correct number of lines are cleared when they are redrawn. I'm not sure I 100% understood how orphan lines work, so I'd appreciate if someone could take a closer look at how I handle them.
The existing examples all run as they did previously, and I've added a new example (`multi-log`) showing the style I was trying to implement when I opened the issue.
One thing I noticed is that calling `clear` on a multiline progress doesn't always seem to clear all progress messages, a random amount stays on the screen even when a message is printed afterwards. I first thought that I introduced that bug, but switching back to …
> Implement multi-line progress message support

- .github/workflows/rust.yml
- Cargo.toml
The latest version of once_cell now requires 1.56. This is old enough at this point that we should just bump our MSRV, too.
> Bump MSRV to 1.56

- .github/workflows/rust.yml
- Cargo.toml
- src/progress_bar.rs
- src/state.rs
https://github.com/taiki-e/portable-atomic
Fixes #475
> Use `portable-atomic` to fix build on some 32-bit platforms

- src/in_memory.rs
- src/state.rs
- src/style.rs
- tests/render.rs
> Fix percent initial value when there is no length

- Cargo.toml
Heya, this allows `indicatif` to compile to WASM. I've checked and `tokio::fs` is not used in the project.
> Remove `"fs"` feature in tokio dependency.

- src/progress_bar.rs
> Update estimate when using a steady ticker

- src/lib.rs
This PR updates the Templates sections's style characters for Alignment, to have a consistent style guide (removing characters that are not actually part of the style) and adding a clarification on what each character does 
fixes #509
> docs(lib): update style reference for alignment characters

- Cargo.toml
- src/draw_target.rs
- src/multi.rs
- src/progress_bar.rs
- src/state.rs
- src/style.rs
> Use `instant::Instant` when compiling to WASM.

- src/draw_target.rs
This adds an optional `rate_limiter` to custom `TermLike` targets, so they don't need to implement rate limiting by hand.
> Allow rate-limiting TermLike targets

- src/progress_bar.rs
> Mention the prefix and message placeholders in the `with_` docs

- src/draw_target.rs
- src/multi.rs
- tests/render.rs
Terminal usually wrap line in case it can't fit the current terminal width. 
This behavior is not taken in account by indicatif and create some visual artifacts.
The issue was reported as #144 (closed with a workaround) and #520.
Please find below a demo **without** the patch:
Demo **with** the patch:
Using #144 example:
> Handle terminal line wrap to avoid new line

- src/progress_bar.rs
- src/state.rs
It makes sense to reset the ETA without resetting the time elapsed back to zero, but when setting the time elapsed back to zero, the ETA should also be reset as this should make the progress bar behave as if it had just been activated (in a partially complete state).
Fixes https://github.com/console-rs/indicatif/issues/536.
> resetting the elapsed time also resets ETA

- src/draw_target.rs
- src/state.rs
- tests/render.rs
Using `println()` with a new line at the beginning of the message trigger some artifacts, see below:
`newline_artifact.rs`
```
use indicatif::ProgressBar;
fn main() {
let pb = ProgressBar::new(1024);
pb.inc(1);
pb.println("\nShould be a new line before this message and no duplicate progress bar");
pb.finish_with_message("done");
}
```
Output on `main`:
Output with this patch:
-----
Using `println()` with an empty string does not trigger new line:
`empty_msg.rs`
```
use indicatif::ProgressBar;
fn main() {
let pb = ProgressBar::new(1024);
pb.inc(1);
pb.println("");
pb.println("There should an empty line before this message");
pb.finish_with_message("done");
}
```
Output on `main`:
Output with this patch:
New test in `render.rs` showcase both issue
> Handle newline in msg and empty msg

- examples/finebars.rs
- examples/morebars.rs
- examples/multi-tree.rs
- examples/multi.rs
- examples/single.rs
- examples/yarnish.rs
> fix: inc after work

- src/in_memory.rs
This method is almost identical to `contents`, but it includes VT-100 codes.
> Add `contents_formatted` to `InMemoryTerm`

- .github/workflows/rust.yml
- Cargo.toml
Fixes #541.
Changelog:
* Handle newline in msg and empty msg (#540, thanks to RDruon)
* Handle terminal line wrap to avoid new line (#533, thanks to RDruon)
* Resetting the elapsed time also resets ETA (#538, thanks to afontenot)
* Mention the prefix and message placeholders in the `with_` docs (#529, thanks to lnicola)
* Allow rate-limiting `TermLike` targets (#526, thanks to akx)
* Fix docs for `ProgressDrawTarget` (#523, thanks to tillarnold)
* Change "OS X" to "macOS" (#519, thanks to atouchet)
* Fix `MultiProgress` alignment handling and migrate from structopt => clap (#516)
* Don't deadlock when double-adding ProgressBar (#515)
* Use `instant::Instant` when compiling to WASM (#514, thanks to azriel91)
* Update portable-atomic requirement from 0.3.15 to 1.0.0 (#512)
* `inc()` after …
> Prepare 0.17.4 release

- tests/multi-autodrop.rs
Seems to be a new or at least tweaked clippy check. It is now causing lint failure.
> tests: suppress clippy redundant clone check in test code

- src/iter.rs
This lets you more concisely set the finish behavior of the progress bar when using `ProgressBarIter`.
For example, to show a progress bar and keep it displayed when it finishes, you can do
```
v.iter().progress().with_finish(ProgressFinish::AndLeave)
```
instead of
```
v.iter()
.progress_with(ProgressBar::new(v.len() as u64).with_finish(ProgressFinish::AndLeave));
```
Closes #545
> Add builder-like `with_finish` method to `ProgressBarIter`.

- src/draw_target.rs
- tests/render.rs
If console::measure_text_width returns 0, the line is effectively empty, although line.is_empty() may still be false. This can for example happen when there is a line which just consists of ANSI color escape sequences.
I hope I didn't undo the work done in #533.
An alternative would be to do:
```
// make sure we never subtract with overflow
let real_len = max(real_len, self.orphan_lines_count + shift);
*last_line_count = real_len - self.orphan_lines_count + shift;
```
closes #546
> Fix subtract with overflow when measuring terminal line length

- Cargo.toml
- src/state.rs
This is an implementation of an exponentially weighted running average with a tuning parameter (currently a constant in this implementation):
* the `ews` parameter is a number of seconds. Progress the `Estimator` has observed that is older than this value will receive a total weight of 0.1 in the rate estimation, and newer values will receive a total of 0.9. The default is 15 seconds.
This implementation does double smoothing by applying the running average to itself. The result avoids undesirable instantaneous movements in the estimate when large updates occur.
The exponential estimator works by keeping a running tally, where an existing tally that has aged `age` seconds is reweighted such that
weight ^ (ewa / age) = 0.1
For instance, data aged 5 seconds with a 15 second weight parameter …
> Switch Estimator to use an exponential weighting 

- src/format.rs
Possible fix for https://github.com/console-rs/indicatif/issues/554, but I wasn't thorough checking for other possible sources of overflow (in particular in the ETA calculation itself, though from a glance it seems OK)
> fix overflow crash when displaying ETA

- Cargo.toml
- src/iter.rs
- src/progress_bar.rs
I've mostly just copied the existing patterns for iterator and asyncread
> feat: add futures::Stream support

- src/draw_target.rs
In `RateLimiter`, the remainder is calculated like this:
```rust
let (new, remainder) = (
elapsed.as_millis() / self.interval as u128,
elapsed.as_nanos() % self.interval as u128 * 1_000_000,
);
```
It looks like remainder is treated as milliseconds (`%` takes place prior to `*`). However, this seems off as it is shown later:
```rust
self.prev = now
.checked_sub(Duration::from_nanos(remainder as u64))
.unwrap();
```
`remainder` is actually used as nanoseconds.
By ~~removing the multiply~~ adjusting the order of calculation, it seems that the rate limiter is much more stable. See this MRE:
```rust
use std::time::Duration;
use indicatif::{ProgressDrawTarget, ProgressStyle};
fn main() {
let pb = indicatif::ProgressBar::with_draw_target(Some(u64::MAX), ProgressDrawTarget::stdout_with_hz(1)); …
```
> fix incorrect remainder calculation in RateLimiter

- src/format.rs
- tests/render.rs
*(I'm new to contributing, please be pedantic (but not opinionated) about the way I contribute.)*
The storage unit without prefix (B, but not KB, KiB...) is not separated from the number by a space, which is incorrect ([see 5.3.3 here](https://www.bipm.org/documents/20126/41483022/si_brochure_8.pdf)) and inconsistent with the formatting of prefixed units (KB, KiB...) in this library.
This is a ***breaking change*** and requires the modification of one test.
> Add missing space before unit

- src/progress_bar.rs
- src/state.rs
When suspending a progress bar which is already inside a multiprogress bar, it should suspend the multiprogress bar.
> Fixed progress bar not suspending multiprogress bar

- README.md
discussed in https://github.com/console-rs/indicatif/pull/569
i tried writing an example too, but that leads to a circular dependency (indicatif_log_bridge depends on indicatif) and two "different" versions of MultiProgress being found, so that did not work out sadly.
> Add new Integrations section to README, containing a link to indicatif_log_bridge initially

- src/draw_target.rs
- tests/render.rs
Fixes #582 
The test `orphan_lines` reproduces the panic. The test `orphan_lines_message_above_progress_bar` tries to ensure that messages are still printed correctly following the fix.
The proposed fix is to effectively ignore `self.orphan_lines_count` many lines from `real_len` when comparing `real_len` to the terminal height.
@oli-obk Would you be able to glance at this? :pray:
> Fix attempt to subtract with overflow (#582)

- src/draw_target.rs
- src/iter.rs
- src/multi.rs
- src/progress_bar.rs
Using `clippy::doc_markdown` showed a couple of minor issues with the docs and then the rest were via visual inspection.
> docs: Improve formatting and linking.

- src/format.rs
This change adds some doc tests to show off what the formatter looks like. This change adds it for just the byte variants:
- `HumanBytes`, which seems to forward to `BinaryBytes`?
- `DecimalBytes`, 1 MB == 1 * 10**6 bytes
- `BinaryBytes`, 1 MiB == 1 * (1 << 20) bytes
I wanted to know what these formatters *look like*, preferably from the docs. This is the simplest way that comes to mind, but I'm open to doing this differently if there's alternatives. I only did the Byte variants with this. I'm happy to work on the others but want to make sure this direction is accepted first.
Here's what my local `rustdoc` docs look like after this change:
These also double as tests, and `cargo test` will fail if their behavior changes.
> Add minimal examples demonstrating Formatters

- src/multi.rs
Fixes #606 -- see added test cases. This logic matches what happens `draw_target.rs` as well. It'll now also correctly handle lines with only ANSI codes.
https://github.com/console-rs/indicatif/blob/81aa4c65d7202128d471b3a452a0236e03f3bc43/src/draw_target.rs#L505-L518
> fix and rename `real_len`

- Cargo.toml
- src/draw_target.rs
- src/multi.rs
An attempt to add a newtype wrapper, as discussed in https://github.com/console-rs/indicatif/issues/612#issuecomment-1853498395 and https://github.com/console-rs/indicatif/issues/612#issuecomment-1860809497.
Notes
1. The wrapper is called `VisualLines` because that was the term introduced in #608, but I am not tied to that name.
2. This PR adds a dependency: [`derive_more`](https://github.com/JelteF/derive_more).
2. I did not modify the `TermLike` trait. It has both "height" and "width" characteristics, and it seemed weird to modify just one.
> Add `VisualLines` newtype wrapper

- src/state.rs
Fixes https://github.com/console-rs/indicatif/issues/601
> Use current position for calculating finished progress bar per_sec instead of bar length

- src/lib.rs
- src/style.rs
- tests/render.rs
The existing `{percent}` is rendered as an integer, which means it is not very useful for large data sets, as it rarely changes.
I suggest adding a new `{percent_precise}` (a non-breaking change?) that would render it with additional precision. For example 3 fraction digits, as demonstrated by the test added here.
An earlier proposal to add precision to variables was rejected (#552), and AFAIK, there is no way to customize this without taking over rendering. I think this proposal would work well with existing variables like `elapsed_precise`, `eta_precise`.
Thanks for considering!
> [feature request] adding `{percent_precise}` style key

- src/style.rs
See for example https://github.com/console-rs/indicatif/actions/runs/8844253603. 
The only thing I can think off is that `colors_enabled` is returning `false`, leading to the unstyled output. If so, this would suggest some kind of race, e.g. in https://github.com/console-rs/console/blob/master/src/utils.rs#L39. But before we go down that rabbit hole let's test the basic theory.
> tests: print whether colors are enabled to help diagnose spurious failure

- src/state.rs
`AtomicPosition::allow` interprets `self.prev` as a number of nanoseconds since `self.start`, but `AtomicPosition::reset` instead stored a number of milliseconds in there. This is a bug, albeit without significant consequences.
I reckon the bug got introduced because the comments are worded a bit ambiguously, so I cleared those up and added a regression test for the future.
> Fix AtomicPosition::reset storing wrong value

- .github/workflows/rust.yml
- Cargo.toml
- src/lib.rs
- src/progress_bar.rs
1. Fix lint failures
2. The default refresh rate is 20 Hz, not 15 Hz as claimed in `ProgressBar::new` documentation
3. Bump MSRV to 1.70 for Tokio 1.39.2
> Documentation tweaks; bump MSRV

- Cargo.toml
- src/draw_target.rs
- src/multi.rs
- src/progress_bar.rs
- src/state.rs
- src/style.rs
Fixes https://github.com/console-rs/indicatif/issues/665. See: https://crates.io/crates/web-time.
Note that unlike `instant`, `web-time` falls back to `std::time` on non-WASM, so this kind of conditional exports are not really necessary:
```rust
#[cfg(not(target_arch = "wasm32"))]
use std::time::Instant;
#[cfg(target_arch = "wasm32")]
use web_time::Instant;
```
Instead, it could unconditionally be `web_time::Instant`, if making `web-time` a (really light, to be fair) dependency on non-WASM platforms as well is acceptable. I can update the PR accordingly, if desired.
> Replace `instant` with `web-time`

- Cargo.toml
The instant dependency will now cause audit issues for all downstream users, so let's get #666 and other accumulated improvements out soon.
> Bump version to 0.17.9

- src/draw_target.rs
- src/multi.rs
- src/state.rs
- src/style.rs
- tests/render.rs
This is my attempt at fixing #447.
The code in `draw_to_term` is a bit of mess, with double definitions, complex branching, and I tried cleaning it up. I introduce a `LineType` enum to differentiate between text, bars and empty lines. The variables names have been renamed to reflect better what they represent. Some code has been shuffled around. Tests pass and I ran examples at random with no issues.
A sample program to understand what this PR wants to fix:
```rs
static LOREM_SMALL: &str = "Lorem ipsum dolor sit amet.";
static LOREM_BIG: &str= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec viverra massa. Nunc nisl lectus,
auctor in lorem eu, maximus elementum est.";
fn generate_logs(manager: &indicatif::MultiProgress, i: u32) {
if i % 20 == 0 {
let _ = …
```
> Fix bar-less text output

- README.md
I wrote this integration between tracing and indicatif a while back, which sees a fair amount of use now, and thought it would be nice to call it out as another integration a la indicatif-log-bridge.
> add tracing-indicatif create to integration list

- src/draw_target.rs
- src/state.rs
When calling `BarState::draw`, there is a call to `self.draw_target.width()`.
However, that operation can be expensive and the width is not needed, if there is no draw-target.
Thus, this PR delays the calling `.width()` if there is not target to draw to.
For comparison, I've used this minibenchmark:
```rust
let bar = ProgressBar::new_spinner();
for n in 0..1_000_000 {
bar.set_message(format!("{}", n));
}
bar.finish();
```
Using the latest release it runs in about 400ms, whilst the fixed version uses about 100ms.
The issue surfaced with uv, when resolving many packages: https://github.com/astral-sh/uv/issues/10384
> Only get draw_target-width when we actually draw

- src/state.rs
Running the snippet of #683 a big chunk of the time is spent in allocating a new string in `TabExpandedString`. Delaying the expanding of tabs reduces the runtime of ~100ms to ~60ms.
The idea is simple: Rather than replacing `\t` with spaces immediately, this is done once `expanded` is actually called.
> Make tab extension lazy

- src/progress_bar.rs
- tests/render.rs
Currently, `ProgressBar:set_tab_with` is the only method that requires `&mut self`.
However, there is no reason that it needs exclusive access, and thus this can be just `&self`.
> Make `ProgressBar:set_tab_with` take `&self`

- examples/multi.rs
SSIA
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/42ee63a3-eb62-4e52-a769-9e94f658962a)|![after](https://github.com/user-attachments/assets/6f83b969-c0a1-423a-9587-a4491b644c55)
> Remove unnecessary spinner display in multi examples

- Cargo.toml
- src/lib.rs
- src/state.rs
The change at [1] stores some data in a `OnceCell`, which made `ProgressStyle` no longer `Sync`. Fix this by changing the `OnceCell` to a `OnceLock`, and add a static test that all relevant public types are `Send` and `Sync`.
[1]: https://github.com/console-rs/indicatif/pull/684
> Change `OnceCell` to `OnceLock` in `TabExpandedString`

- src/progress_bar.rs
Allow users to force a redraw of the progress bar.
This should normally not be needed, since there are more idiomatic ways to ensure that the progress bar is up to date.
Also, I've noticed that other ways to enforce redrawing (`.suspend()`) can lead to flickering, while `.force_draw()` does not.
Adresses: #688
> Add ProgressBar::force_draw

- src/format.rs
- src/style.rs
- Use `width` to truncate `HumanFloatCount` values 
- Normally float truncation is done by using `.#`, but in `indicatif` `.` is reserved for specifying a style string.
- Resolves #485 and #663
Examples:
`"{spinner:.green} [{elapsed}] [{bar:.blue}] {human_pos}/{human_len} ({per_sec:0}, ETA: {eta})"`:
`"{spinner:.green} [{elapsed}] [{bar:.blue}] {human_pos}/{human_len} ({per_sec:4}, ETA: {eta})"`:
> Use width to truncate `HumanFloatCount` values
